apps/fromDjangoToXLSXApp/urls.py
from django.urls import path
from . import views

app_name = 'fdtxa'
urlpatterns = [
    path('reporte',views.Generar_xlsx.as_view(),name='reporte')
    ]

pruebaFrancisco/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

from  django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.fromDjangoToXLSXApp.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',serve, {'document_root' : settings.MEDIA_ROOT,}),
        #path('media/<path>.*',serve,{'document_root' : settings.MEDIA_ROOT,})
    ]

apps/fromDjangoToXLSXApp/models.py
from django.db import models
from .choices import PRIMERA, PAR, OPT, BYMAIL


class Customer(models.Model):
    idCustomer = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    parser = models.CharField(max_length=1, choices=PAR)

    def __str__(self):
        return self.name

class FileParse(models.Model):
    idFileParser = models.AutoField(primary_key=True)
    customerId = models.ForeignKey(Customer, on_delete=models.CASCADE)
    emailId = models.IntegerField(null=True)
    emailDate = models.DateField()
    parser = models.CharField(max_length=1, choices=PAR, default=PRIMERA)
    option = models.CharField(max_length=20, choices=OPT, default=BYMAIL)
    sended = models.BooleanField(default=False)
    file = models.FileField()
    created = models.DateTimeField(auto_now_add=True,editable=False, null=True)

    def __str__(self):
        return str(self.customerId)+" - "+self.option

apps/fromDjangoToXLSXApp/forms.py
import datetime

from django import forms
from bootstrap_datepicker_plus import DatePickerInput

from  .models import FileParse, Customer
from .choices import ESTILO, TRUE_FALSE_CHOICES, FILTER

class FileParseForm(forms.Form):


    customer_id = forms.ModelChoiceField(queryset=Customer.objects.all(),
                                         widget=forms.Select(attrs={'class': 'form-control'}), required=True)

    sended = forms.ChoiceField(choices=TRUE_FALSE_CHOICES, label="Enviado",
                               initial='', widget=forms.Select(attrs={'class': 'form-control'}), required=True)

    filter = forms.ChoiceField(choices=FILTER, label="Filtro",
                               initial='', widget=forms.Select(attrs={'class': 'form-control'}), required=True)

    fecha_ini = forms.DateField(label='Fecha Inicial', widget=DatePickerInput(format='%Y-%m-%d'))
    fecha_fin = forms.DateField(label='Fecha Final', widget=DatePickerInput(format='%Y-%m-%d'))

    style = forms.ChoiceField(choices=ESTILO, label="Estilo del Reporte",
                               initial=1, widget=forms.Select(attrs={'class': 'form-control'}), required=True)



    def clean(self):
        cleaned_data = super(FileParseForm, self).clean()
        fecha_ini = cleaned_data.get('fecha_ini')
        fecha_fin = cleaned_data.get('fecha_fin')
        if fecha_fin <= datetime.date.today():
            if fecha_ini > fecha_fin:
                raise forms.ValidationError("Fecha inicial no puede ser mayor a la fecha final")
        else:
            raise forms.ValidationError("Fecha final no puede ser mayor a hoy")

        return cleaned_data

apps/fromDjangoToXLSXApp/views.py
from datetime import datetime

from django.shortcuts import render
from openpyxl import Workbook


from django.http import HttpResponse
from django.views.generic import TemplateView


from .models import FileParse
from .forms import FileParseForm
from .tasks import get_post_req
from .functions import give_style, load_excel

class Generar_xlsx(TemplateView):
    model = FileParse
    template_name = 'fromDjangoToXLSX/filtro.html'
    form_class = FileParseForm

    def get(self,request):
        return render(request, self.template_name,{'form': self.form_class})

    def form_invalid(self, form):
        return super(Generar_xlsx,self).form_invalid(form)




    def post(self,request):

        my_form = FileParseForm(request.POST)
        if my_form.is_valid():

            filtered = request.POST['filter']
            customer = request.POST['customer_id']
            date_ini = request.POST['fecha_ini']
            date_fin = request.POST['fecha_fin']
            sended = request.POST['sended']
            style = request.POST['style']

            info_list = get_post_req.delay(filtered, customer, date_ini, date_fin, sended).get()


            workbook = Workbook()
            worksheet = workbook.active
            worksheet.title = 'FileParse'

            worksheet['B1'] = 'REPORT'

            worksheet.merge_cells('B1:G1')

            titles = ['customer', 'emailId', 'parse', 'option', 'file_name', 'creation']


            first_line = 4
            load_excel(info_list, first_line, worksheet)

            line_title = 2

            my_style = give_style(style)

            for col_num, column_title in enumerate(titles, 2):
                cell = worksheet.cell(row=line_title, column=col_num)
                cell.value = column_title
                cell.font = my_style.get('fuente')
                cell.border = my_style.get('borde')
                cell.alignment = my_style.get('alineacion')
                cell.fill = my_style.get('relleno')




            response = HttpResponse(
                content_type = 'application/ms-excel'
            )
            response['Content-Disposition'] = 'attachment; filename = report_{date}.xlsx'.format(
                date=datetime.now().strftime("%d%m%Y-%H%M%S"),
            )


            workbook.save(response)

            return response

        return render(request, "fromDjangoToXLSX/filtro.html", {'form':my_form})

templates/fromDjangoToXLSX/base.html
{% load staticfiles %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
{% block header %}
{% endblock header %}
{% block content %}
{% endblock content %}
{% block footer %}
{% endblock footer %}
</body>
</html>

templates/fromDjangoToXLSX/filtro.html
{% extends 'fromDjangoToXLSX/base.html' %}

{% block content %}
    <div class="container">
        <div class="card form-group otraclase">
            <div class="card-header">
                <h5 class="text-center">DOCUMENT EXPORTER REPORT</h5>
            </div>
                <form class="p-2" method="post" action="{%  url 'fdtxa:reporte' %}">
                   {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="btn btn-outline-primary">Export</button>
                </form>
        </div>
    </div>
{% endblock content %}